### ISSUE TITLE
PxrMatteID - not supported

### ISSUE THREAD

**Issue by nyue** [ababak/maya2katana#1] opened 2018-05-10 18:53 UTC
Error: line 1: int() argument must be a string or a number, not 'tuple'
Traceback (most recent call last):
  File "<maya console>", line 3, in <module>
  File "W:\PubLogs\nyue\maya\maya2katana\clip.py", line 530, in copy
    xml = generateXML(nodeNames, renderer=renderer)
  File "W:\PubLogs\nyue\maya\maya2katana\clip.py", line 512, in generateXML
    nodeXml = processNode(node, renderer=renderer, mappings=renderer_module.mappings)
  File "W:\PubLogs\nyue\maya\maya2katana\clip.py", line 273, in processNode
    iterateMappingRecursive(mappings[nodeType], root, node)
  File "W:\PubLogs\nyue\maya\maya2katana\clip.py", line 169, in iterateMappingRecursive
    if mayaValue is not None and not equalAttributes(mayaValue, value):
  File "W:\PubLogs\nyue\maya\maya2katana\clip.py", line 76, in equalAttributes
    return int(a) == int(b)
TypeError: int() argument must be a string or a number, not 'tuple' #

**Comment by ababak** [comment] 2018-05-11 13:05
Fixed in the latest commit.
Additionally, now you can connect several utility patterns and that will translate to ShadingNodeArrayConnector in Katana.

**Closed as completed by ababak** 2018-05-11 13:05 UTC

**Comment by ababak** [comment] 2018-05-13 13:55
@nyue 
Hi Nicholas, please confirm that the issue is fixed for you.

**Comment by nyue** [comment] 2018-05-13 17:42
@ababak this has been resolved. Thank you.
